import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';

part 'main_dashboard_state.dart';
part 'main_dashboard_cubit.freezed.dart';

@injectable
class MainDashboardCubit extends Cubit<MainDashboardState>{
  MainDashboardCubit() : super(const MainDashboardState.initialized());

  void init() {
    emit(const MainDashboardState.loading());

    final List<Post> list = [
      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),
            Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      ),      Post(
        'https://i.pinimg.com/564x/cb/67/77/cb6777e04ef147add461283e9da16395.jpg', 
        'XFDDDDDDDDDDDDDD', 
        'XDFDSFBVCVHGFVBHGFVBNJYTGFCV BNHGFVC BNHJYGFCV NBHGFVBNJHGFVC NJHYGVC  NHGVC NHGVC  VBHGVC NJUYGVC NJUYTGFVC NJUYTGFVC NJYHGFVC MJUHGV  NMJHGV  MJHGV  NJHGV  MNJHGV NMJHGV MKJUYHGV  NJHGV NMJUYHGV '
      )
    ];

    emit(MainDashboardState.postLoaded(list));
  }
}


class Post{
  final String link;
  final String title;
  final String description;

  Post(this.link, this.title, this.description);
}